language: objective-c
osx_image: xcode9.1
script: set -o pipefail && xcodebuild test -project MoneyExample.xcodeproj -scheme MoneyExample -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.1' ONLY_ACTIVE_ARCH=NO | xcpretty